workflow:
  save_to_db: True

communities:
  processed_data:
    path: back/tests/data/communities/
    all_communities_file: all_communities_data.parquet
    selected_communities_file: selected_communities_data.parquet

  ofgl:
    url:
      regions: https://data.ofgl.fr/explore/dataset/ofgl-base-regions-consolidee/download/?format=csv&disjunctive.reg_name=true&disjunctive.agregat=true&refine.agregat=D%C3%A9penses+totales&refine.exer=2020&timezone=Europe/Berlin&lang=fr&use_labels_for_header=true&csv_separator=%3B
      departements: https://data.ofgl.fr/explore/dataset/ofgl-base-departements-consolidee/download/?format=csv&disjunctive.reg_name=true&disjunctive.dep_tranche_population=true&disjunctive.dep_name=true&disjunctive.agregat=true&refine.exer=2020&refine.agregat=D%C3%A9penses+totales&timezone=Europe/Berlin&lang=fr&use_labels_for_header=true&csv_separator=%3B
      communes: file:./back/tests/inputs/ofgl-base-communes-consolidee.test.csv
      intercos: https://data.ofgl.fr/explore/dataset/ofgl-base-gfp-consolidee/download/?format=csv&disjunctive.dep_name=true&disjunctive.gfp_tranche_population=true&disjunctive.nat_juridique=true&disjunctive.mode_financement=true&disjunctive.gfp_tranche_revenu_imposable_par_habitant=true&disjunctive.epci_name=true&disjunctive.agregat=true&refine.exer=2020&refine.agregat=D%C3%A9penses+totales&timezone=Europe/Berlin&lang=fr&use_labels_for_header=true&csv_separator=%3B
    dtype:
      Code Insee 2023 Région: str
      Code Insee 2023 Département: str
      Code Insee 2023 Commune: str
    processed_data:
      path: back/tests/data/ofgl/
      filename: ofgl_data.csv

    epci:
      file: back/data/communities/scrapped_data/gouv_colloc/epcicom2023.xlsx
      dtype:
        siren: str
        siren_membre: str

  odf:
    url: https://static.data.gouv.fr/resources/donnees-de-lobservatoire-open-data-des-territoires-edition-2022/20230202-112356/indicateurs-odater-organisations-2022-12-31-.csv
    dtype:
      siren: str
    processed_data:
      path: back/tests/data/odf/
      filename: odf_data.csv

  geolocator:
    epci_coords_scrapped_data_file: back/data/communities/scrapped_data/geoloc/epci_geolocs.csv
    reg_dep_coords_scrapped_data_file: back/data/communities/scrapped_data/geoloc/dep_reg_centers.csv
    geolocator_api_url: https://api-adresse.data.gouv.fr/search/csv/
    temp_folder:
      path: back/tests/data/geolocator/
      filename: cities_to_geolocate.csv

datagouv:
  datasets:
    url: https://www.data.gouv.fr/fr/datasets/r/f868cca6-8da1-4369-a78d-47463f19a9a3
    columns:
      - "id"
      - "title"
      - "url"
      - "description"
      - "organization"
      - "organization_id"
      - "frequency"
  datafiles:
    url: "file:./back/tests/inputs/datagouv-datafiles-10000.csv"
  paths:
    root: back/tests/data/datagouv_search
    organization_datasets: organization_datasets
  files:
    catalog: datagouv_catalog.parquet
    catalog_metadata: catalog_metadata.parquet
    datasets: datagouv_datasets.parquet

search:
  subventions:
    source: "multiple"
    title_filter: (?:conventions de subvention|subv.*asso|subvention.*association|Subventions du Conseil Régional|Interventions de la Région des Pays de la Loire|SCDL - Subventions)
    description_filter: (?:conventions de subvention|subvention.*association|subv.*asso)
    api:
      testIds:
        - 534fffa7a3a7292c64a780c5
        - 534fffada3a7292c64a780f9
      url: "https://www.data.gouv.fr/api/1/datasets/"
      title:
        - "association"
        - "subvention"
        - "intervention"
        - "aide"
        - "versement"
      description:
        - "association"
        - "subvention"
        - "intervention"
        - "aide"
        - "versement"
      columns:
        - "montant"
    schema:
      url: "https://schema.data.gouv.fr/schemas/scdl/subventions/2.1.0/schema.json"
    single_urls_file: back/tests/inputs/single_urls_2.csv
    schema_dict_file: back/data/datasets/subventions/inputs/dataset_dict.csv
  marches_publics:
    source: "single"
    unified_dataset:
      url: "file:./back/tests/inputs/decp-2019-10000.json"
      root: "marches"
    schema:
      url: "https://schema.data.gouv.fr/schemas/139bercy/format-commande-publique/1.5.0/marches.json"
      name: "marche"

datafile_loader:
  data_folder: 'back/tests/data/datasets/%(topic)s'
  combined_filename: 'back/tests/data/datasets/%(topic)s.parquet'
  file_info_columns:
    - "siren"
    - "organization"
    - "title"
    - "created_at"
    - "url"
    - "nom"
    - "type"
    - "source"

file_age_to_check:
  files: {}
  age: 365


elected_officials:
  data_folder: back/tests/data/elected_officials

sirene:
  data_folder: back/tests/data/sirene
  url: file:./tests/back/datasets/fixtures/StockUniteLegale_utf8.zip

datagouv_api:
  organization_folder: back/tests/data/datagouv_api/organizations

declarations_interet:
  data_folder: back/tests/data/declarations_interet
  url:  file:./tests/back/datasets/fixtures/declaration.xml

outputs_csv:
  path: 'back/tests/data/datasets/%(topic)s/outputs'

warehouse:
  data_folder: back/tests/data/warehouse

logging:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: DEBUG
      formatter: simple
      filename: back/data/logs/log.txt
  loggers:
    back:
      level: INFO
      handlers: [console, file]